ModusWeb/Models/NewsFeed.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ModusWeb.Models
{
    public class News    {
        public string Title { get; set; }

        [Url]
        public string URL { get; set; }

        public string Description { get; set; }

        public DateTime Date { get; set; }
    }

    public class NewsFeeds
    {
        public List<News> NewsFeedList {get; set;}
    }

   
}

ModusWeb/Models/SourceModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ModusWeb.Controllers
{
    public class SourceModels
    {
        public int SourceId { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
    }
}

ModusWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ModusWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ModusWeb/Controllers/NewsFeedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;
using ModusWeb.FeedNewsManage;
using ModusWeb.Models;

namespace ModusWeb.Controllers
{
    public class NewsFeedController : Controller
    {

        private NewsManage logic = new NewsManage();

        // GET: NewsFeed
        public ActionResult Index()
        {
            var source = logic.GetSources();
            ViewBag.SOURCE = source;
            return View();
        }

        [HttpPost]
        public ActionResult Index(string providerURL)
        { 
            var data = logic.GetNews( providerURL);
            ViewBag.URL = providerURL;
            var source = logic.GetSources();
            ViewBag.SOURCE = source;
            return View(data);
        }
    }
}

ModusWeb/Controllers/SourcesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ModusWeb.DataAccess;
using System.Reflection;
using System.Xml.Linq;

namespace ModusWeb.Controllers
{
    public class SourcesController : Controller
    {
        private LocalDBEntities db = new LocalDBEntities();

        // GET: Sources
        public async Task<ActionResult> Index()
        {
            return View(await db.Sources.ToListAsync());
        }

        // GET: Sources/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Source source = await db.Sources.FindAsync(id);
            if (source == null)
            {
                return HttpNotFound();
            }
            return View(source);
        }

        // GET: Sources/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sources/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "SourceId,Url,Description")] Source source)
        {
            if (!string.IsNullOrEmpty(source.Url))
            {
                try
                {
                    WebClient wclient = new WebClient();
                    string newsData = wclient.DownloadString(source.Url);

                    XDocument xml = XDocument.Parse(newsData);
                    if (ModelState.IsValid)
                    {
                        db.Sources.Add(source);
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }
                }
                catch
                {

                }
            }


            return View(source);
        }

        // GET: Sources/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Source source = await db.Sources.FindAsync(id);
            if (source == null)
            {
                return HttpNotFound();
            }
            return View(source);
        }

        // POST: Sources/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "SourceId,Url,Description")] Source source)
        {
            if (!string.IsNullOrEmpty(source.Url))
            {
                try
                {
                    WebClient wclient = new WebClient();
                    string newsData = wclient.DownloadString(source.Url);

                    XDocument xml = XDocument.Parse(newsData);
                    if (ModelState.IsValid)
                    {
                        db.Entry(source).State = EntityState.Modified;
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }
                }
                catch
                {

                }
            }
            return View(source);
        }

        // GET: Sources/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Source source = await db.Sources.FindAsync(id);
            if (source == null)
            {
                return HttpNotFound();
            }
            return View(source);
        }

        // POST: Sources/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Source source = await db.Sources.FindAsync(id);
            db.Sources.Remove(source);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ModusWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ModusWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ModusWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ModusWeb/Views/NewsFeed/Index.cshtml
@{
    ViewBag.Title = "News";
}
<script src="~/Scripts/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });

    $(document).on("click", ".open-NewsDialog", function () {
        var url = $(this).data('id');
        $(".modal-body #urlst")[0].data = url;

    });
</script>
<br />
<h2>Modus News</h2>
<hr />
<br />
@using (Html.BeginForm())
{
    <div style="position:relative">


        @if (ViewBag.SOURCE.Count>0)
        {
            <select name="providerURL"  style="min-width:90%">
                <option value="">Select all</option>
                @foreach (var item in ViewBag.SOURCE)
                {
                <option value="@item">@item</option>

                }
            </select>
        }
        else
        {
            <input type="URL" name="providerURL" placeholder="Enter URL Here..." value="@ViewBag.URL" style="min-width:90%" />
        }


        <input type="submit" class="btn btn-success" value=" >>" />
    </div>
}
<br><br>
<input id="myInput" type="text" placeholder="Search..">
<br><br>
<table class="table table-hover">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th style="width:15%">Publish Date</th>
            <th style="width:10%">Actions</th>
        </tr>
    </thead>
    <tbody id="myTable">

        @if (Model != null)
        {
            foreach (var item in Model.NewsFeedList)
            {
                <tr>
                    <td>@item.Title</td>
                    <td title="@item.Description">@(@item.Description.Length>=150? @item.Description.Substring(0, 150):@item.Description)</td>
                    <td>@item.Date</td>
                    <td>
                        <a href="@item.URL" target="_blank">Go</a>
                        <button type="button" class=" btn-link open-NewsDialog" data-id="@item.URL" data-toggle="modal" data-target="#ModalNew">View</button>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<!-- Modal to show the news -->
<div class="modal fade" id="ModalNew" tabindex="-1" role="dialog" aria-labelledby="ModalNewTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalNewTitle">News</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="margin: 0 auto; width:100%; height:400px;">
                <object type="text/html" name="urlst" id="urlst" data="#"
                        style="width:100%; height:100%; margin:1%;"></object>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

ModusWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Read News", "Index", "NewsFeed")</li>
                    <li>@Html.ActionLink("Manage Source", "Index", "Sources")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ModusWeb/Views/Sources/Create.cshtml
@model ModusWeb.DataAccess.Source

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Source</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ModusWeb/Views/Sources/Delete.cshtml
@model ModusWeb.DataAccess.Source

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Source</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ModusWeb/Views/Sources/Details.cshtml
@model ModusWeb.DataAccess.Source

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Source</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Url)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Url)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.SourceId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ModusWeb/Views/Sources/Edit.cshtml
@model ModusWeb.DataAccess.Source

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Source</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.SourceId)

        <div class="form-group">
            @Html.LabelFor(model => model.Url, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Url, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Url, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ModusWeb/Views/Sources/Index.cshtml
@model IEnumerable<ModusWeb.DataAccess.Source>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Url)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.SourceId }) |
            @Html.ActionLink("Details", "Details", new { id=item.SourceId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.SourceId })
        </td>
    </tr>
}

</table>